# Generated by Django 3.2.6 on 2021-08-19 18:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user_image', models.ImageField(upload_to='images/')),
                ('job_title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('personal_info', models.TextField(default='a summary about yourself')),
                ('key_skills', models.TextField()),
                ('job_title_c', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description_c', models.TextField()),
                ('university_name', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('description_u', models.TextField()),
            ],
        ),
    ]
